### ISSUE TITLE
Link in README.md ain't workin

### ISSUE THREAD

**Issue by jlwin** [paslandau/docker-php-tutorial#1]
Dude, get ya README file together and fix that damn link to your tutorial!

**Comment by paslandau** [comment]
Hey @jlwin,

thank you so much for filing this bug! You'll find the correct link in at [https://github.com/paslandau/docker-php-tutorial/blob/part_1/README.md](https://www.youtube.com/watch?v=DLzxrzFCyOs)

All the best
Pascal
