### ISSUE TITLE
Part_3 doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by undertheflag** [paslandau/docker-php-tutorial#2]
I am a newbee, following the ReadMe and changing the compose version to '3.3', always encounters errors with :
`docker-compose -f ./.docker/docker-compose.yml --project-directory ./.docker rm -fs  && \
docker-compose -f ./.docker/docker-compose.yml --project-directory ./.docker build --pull --no-cache --parallel  && \
docker-compose -f ./.docker/docker-compose.yml --project-directory ./.docker up -d --force-recreate 
WARNING: The NGINX_HOST_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The NGINX_HOST_HTTPS_PORT variable is not set. Defaulting to a blank string.
WARNING: The APP_HOST variable is not set. Defaulting to a blank string.
WARNING: The APP_CODE_PATH_HOST variable is not set. Defaulting to a blank string.
WARNING: The APP_CODE_PATH_CONTAINER variable is not set. Defaulting to a blank string.
WARNING: The APP_GROUP variable is not set. Defaulting to a blank string.
WARNING: The APP_GROUP_ID variable is not set. Defaulting to a blank string.
WARNING: The APP_USER variable is not set. Defaulting to a blank string.
WARNING: The APP_USER_ID variable is not set. Defaulting to a blank string.
WARNING: The TIMEZONE variable is not set. Defaulting to a blank string.
WARNING: The PHP_VERSION variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_HOST_SSH_PORT variable is not set. Defaulting to a blank string.
WARNING: The NETWORKS_DRIVER variable is not set. Defaulting to a blank string.
ERROR: The Compose file '././.docker/docker-compose.yml' is invalid because:
services.workspace.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
Makefile:23: recipe for target 'docker-build-from-scratch' failed
make: *** [docker-build-from-scratch] Error 1
`
Hoping supports for Linux.

**Comment by paslandau** [comment]
Hey @undertheflag,

looks like the .env file is not recognized (hence the ` WARNING: The ... variable is not set`).

Also 
> changing the compose version to '3.3'
Might yield unexpected behavior since I only tested with 3.7

Please make sure to stick to the same version.
