### ISSUE TITLE
How to login via ssh

### ISSUE THREAD

**Issue by liamka** [paslandau/docker-php-tutorial#6]
Can we set password for ssh? Login is _www-data_?

**Comment by paslandau** [comment]
Please refer to the updated article at https://www.pascallandau.com/blog/docker-from-scratch-for-php-applications-in-2022/

=> https://github.com/paslandau/docker-php-tutorial/blob/part-4-1-docker-from-scratch-for-php-applications-in-2022/.docker/.env.example#L9
